### ISSUE TITLE
Using Networkx 2.x breaks graphgen

### ISSUE THREAD

**Issue by isi-lincoln** [ISIEdgeLab/graphGen#2]
Networkx 1.11 module works with the following output:

```
root@0c0d1aef5c86:/graphGen# ./graphgen/graphGen.py -d test.png test.xnet 
/usr/local/lib/python2.7/site-packages/networkx-1.11-py2.7.egg/networkx/drawing/nx_pylab.py:522: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  if not cb.is_string_like(edge_color) \
/usr/local/lib/python2.7/site-packages/networkx-1.11-py2.7.egg/networkx/drawing/nx_pylab.py:543: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  if cb.is_string_like(edge_color) or len(edge_color) == 1:
/usr/local/lib/python2.7/site-packages/networkx-1.11-py2.7.egg/networkx/drawing/nx_pylab.py:724: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  if not cb.is_string_like(label):
```

While networkx 2.0 (latest stable):

```
root@7eb951d74a27:/graphGen# graphgen/graphGen.py -d test.png test.xnet 
Traceback (most recent call last):
  File "graphgen/graphGen.py", line 328, in <module>
    main()
  File "graphgen/graphGen.py", line 315, in main
    gen = GraphGen(args.infile, args.routes, cmdline=sys.argv)
  File "graphgen/graphGen.py", line 22, in __init__
    self.readGraph(filename)
  File "graphgen/graphGen.py", line 43, in a
    nx.set_edge_attributes(self.g, 's_elements', push_elements)
  File "/usr/local/lib/python2.7/site-packages/networkx/classes/function.py", line 763, in set_edge_attributes
    data[name] = values
TypeError: unhashable type: 'dict'
```

**Comment by isi-lincoln** [comment]
Fixed in https://github.com/ISIEdgeLab/graphGen/pull/4
